package cidr

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestLPMKeyByteLayout_GoebpfParity verifies NEW-UT-02 (§8.1.2): the
// hand-rolled makeLPMv4Key / makeLPMv6Key helpers produce byte-identical
// output to goebpf's CreateLPMtrieKey → KeyValueToBytes path captured
// before the migration, for eight canonical CIDRs spanning prefix length
// extremes and both address families.
//
// Fixture: node/agent/cidr/testdata/lpm_keys_goebpf.json, generated by
// `go run ./cmd/dump_lpm_keys` while goebpf was still the runtime loader
// (Phase 0). Any byte-level divergence between pre- and post-migration
// keys would silently break LPM lookups in the kernel, so this test is a
// merge gate for Phase 2.
func TestLPMKeyByteLayout_GoebpfParity(t *testing.T) {
	type fixture struct {
		CIDR   string `json:"cidr"`
		Family int    `json:"family"`
		KeyLen int    `json:"key_len"`
		HexKey string `json:"hex_key"`
	}

	path := filepath.Join("testdata", "lpm_keys_goebpf.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture %s: %v", path, err)
	}

	var items []fixture
	if err := json.Unmarshal(raw, &items); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	if len(items) == 0 {
		t.Fatal("fixture is empty")
	}

	for _, item := range items {
		item := item
		t.Run(item.CIDR, func(t *testing.T) {
			want, err := hex.DecodeString(item.HexKey)
			if err != nil {
				t.Fatalf("decode fixture hex: %v", err)
			}
			if len(want) != item.KeyLen {
				t.Fatalf("fixture inconsistency: key_len=%d but hex decodes to %d bytes",
					item.KeyLen, len(want))
			}

			var buf bytes.Buffer
			switch item.Family {
			case 4:
				k, err := makeLPMv4Key(item.CIDR)
				if err != nil {
					t.Fatalf("makeLPMv4Key(%q): %v", item.CIDR, err)
				}
				if err := binary.Write(&buf, binary.LittleEndian, k); err != nil {
					t.Fatalf("serialise v4 key: %v", err)
				}
			case 6:
				k, err := makeLPMv6Key(item.CIDR)
				if err != nil {
					t.Fatalf("makeLPMv6Key(%q): %v", item.CIDR, err)
				}
				if err := binary.Write(&buf, binary.LittleEndian, k); err != nil {
					t.Fatalf("serialise v6 key: %v", err)
				}
			default:
				t.Fatalf("unknown family %d", item.Family)
			}

			got := buf.Bytes()
			if !bytes.Equal(got, want) {
				t.Fatalf("byte layout mismatch for %s\n  want %x\n  got  %x",
					item.CIDR, want, got)
			}
		})
	}
}

// TestMakeLPMv4Key_IPv6Rejected ensures the v4 helper refuses an IPv6 input
// instead of silently emitting a truncated key.
func TestMakeLPMv4Key_IPv6Rejected(t *testing.T) {
	if _, err := makeLPMv4Key("2001:db8::/32"); err == nil {
		t.Fatal("expected error when passing IPv6 CIDR to makeLPMv4Key")
	}
}

// TestMakeLPMv6Key_IPv4Accepted confirms the v6 helper accepts IPv4 inputs
// (as IPv4-in-IPv6) — symmetry with goebpf's prior behaviour where a /32
// IPv4 in the v6 helper was valid. If we ever tighten this, update the
// expectation here.
func TestMakeLPMv6Key_IPv4Accepted(t *testing.T) {
	// net.ParseCIDR("10.0.0.0/8") returns an IPv4 mask; To16() lifts it.
	if _, err := makeLPMv6Key("10.0.0.0/8"); err != nil {
		t.Fatalf("makeLPMv6Key with IPv4 CIDR: %v", err)
	}
}
